# Generated by Django 3.1.2 on 2020-11-09 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technologies',
            old_name='techno_name',
            new_name='techno',
        ),
    ]
